config/routes.rb
BaseApp::Application.routes.draw do

  resources :morale

  get 'notifications/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "users/registrations"}

  get "home/index"
  resources :war
  resources :army do
    collection do
      resources :recruit
    end
  end
  resources :market
  resources :structures
  resources :items
  resources :spells do
    member do
      get 'cast', action: :cast
    end
  end
  resources :activities do
    collection do
      post 'explore', action: :explore
      post 'collect', action: :collect
      post 'build', action: :build
      post 'destroy', action: :destroy
      post 'disband', action: :disband
      post 'recruit', action: :recruit
      post 'party', action: :party
      post 'payoff', action: :payoff
      post 'cast', action: :cast
    end
  end
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  root :to => "homes#index"

end

app/views/shared/_back.html.haml
.back.container
  .row
    =link_to '<back', root_path

app/views/shared/_explore.html.haml
.right
  -if current_user.is_exploring?
    = "Exploration: #{distance_of_time_in_words(current_user.explore_end, Time.now, include_seconds:true)} left"
  -else
    = form_tag("/activities/explore", method: "post") do
      = submit_tag("Explore", class:"btn btn-default btn-sm")

app/views/shared/_home_pic.html.haml
-get_home_page(page)
.panel.panel-default
  .panel-body.no-margin.no-padding
    .home-pic.col-xs-12.col-md-12.col-lg-12{style:"background-image: url('#{asset_path @filename}');#{@percentage};#{@opt1}"}
      .absolute.pagename
        =@page.capitalize
      .absolute.view-notifications
        =link_to "N", notifications_index_path, class:"btn btn-default"

app/views/shared/_notifications.html.haml
-#Add new attribute to User_notifications(where show_to_user:true)
-uns = current_user.user_notifications.where(viewed:false)
-if uns.present?
  .alert.alert-warning.alert-dismissible{:role => "alert"}
    %button.close{"data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"}×
      %span.sr-only Close
    -uns.each do |un|
      .row
        = UserNotification.render_message(un, current_user)

app/views/shared/_status.html.haml
-gold_perc = ((current_user.uncollected_gold.to_f/@max_carry_gold) * 100).ceil
-mana_perc = ((current_user.uncollected_mana.to_f/@max_carry_mana) * 100).ceil

.panel.panel-default
  .panel-heading= "Status: (Updates on the hour) #{time_till_next_update} untill next update"
  %table.table
    %tbody
      %tr
        %td.text-right Gold:
        %td.text-left="#{current_user.gold}"
        %td.text-right=current_user.uncollected_gold == @max_carry_gold ? "(Full)" : "#{@gold_per_refresh}"
        %td{style:"width:50%"}
          .progress{style:"margin-bottom:0"}
            .progress-bar.progress-bar-warning{"aria-valuemax" => "#{@max_carry_gold}",
            "aria-valuemin" => "20", "aria-valuenow" => "#{current_user.uncollected_gold}", :role => "progressbar",
            style: "width: #{gold_perc}%;"} #{current_user.uncollected_gold}
        %td
          = form_tag("activities/collect", method: "post") do
            = hidden_field_tag "resource", 'gold'
            = submit_tag("Collect Tribute", class:'btn btn-default btn-xs')
      %tr
        %td.text-right Mana:
        %td.text-left="#{current_user.mana}/#{@mana_capacity}"
        %td.text-right=current_user.uncollected_mana == @max_carry_mana ? "(Full)" : "#{@mana_per_refresh}"
        %td
          .progress{style:"margin-bottom:0"}
            .progress-bar.progress-bar-info{"aria-valuemax" => "#{@max_carry_mana}",
            "aria-valuemin" => "20", "aria-valuenow" => "#{current_user.uncollected_mana}", :role => "progressbar",
            style: "width: #{mana_perc}%;"} #{current_user.uncollected_mana}
        %td
          = form_tag("activities/collect", method: "post") do
            = hidden_field_tag "resource", 'mana'
            = submit_tag("Collect Prayer", class:'btn btn-default btn-xs')
      %tr
        %td{colspan:5}
          ="Payment for your troops are deducted with each update.  If you can't pay them, their morale will lower.  With lower morale, you have an increased chance for units abandoning you."
      %tr
        %td.text-right{style:"width:15%"}
          %span=link_to "<i class='fa fa-info-circle'></i>".html_safe, "#", class:"favor-info",title: "Favor Help", tabindex: 0,
                      data: { toggle: "popover", trigger:"focus", content: "The higher the favor, the more successful you will be when recruiting troops.  Troops will also be far less willing to abandon your cause" }
          ="Favor"
        %td{colspan:3,style:"width:50%"}
          .progress{style:"margin-bottom:0"}
            .progress-bar.progress-bar-warning{"aria-valuemax" => "100",
            "aria-valuemin" => "0", "aria-valuenow" => "#{current_user.favor}", :role => "progressbar",
            style: "width: #{current_user.favor}%;"} #{current_user.favor}
        %td
          =link_to("Raise Morale", '/morale', class:'btn btn-default btn-xs')
:javascript
  $(document).ready(function(e){
    $(".favor-info").popover({placement : 'right' }).on('click', function(e) {e.preventDefault(); return true;});
  });