config/routes.rb
BaseApp::Application.routes.draw do

  resources :morale

  get 'notifications/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "users/registrations"}

  get "home/index"
  resources :war
  resources :army do
    collection do
      resources :recruit
    end
  end
  resources :market
  resources :structures
  resources :items
  resources :spells do
    member do
      get 'cast', action: :cast
    end
  end
  resources :activities do
    collection do
      post 'explore', action: :explore
      post 'collect', action: :collect
      post 'build', action: :build
      post 'destroy', action: :destroy
      post 'disband', action: :disband
      post 'recruit', action: :recruit
      post 'party', action: :party
      post 'payoff', action: :payoff
      post 'cast', action: :cast
    end
  end
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  root :to => "homes#index"

end

app/models/spell.rb
class Spell < ActiveRecord::Base
  has_many :user_spells, dependent: :delete_all
  has_many :users, :through => :user_spells

  has_many :spell_buffs
  has_many :buff_effects, :through => :spell_buffs

  scope :target_self, -> { where(target: 'self') }
  scope :target_enemy, -> { where(target: 'enemy') }
  scope :target_friend, -> { where(target: 'friend') }

  class << self
    %w(serenity deforestation).each do |spell|
      spell = spell.capitalize
      define_method spell.to_sym do
        where(name: spell).first
      end
    end
  end

end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_spells, :index

  def index
    @page = 'spells'
  end

  def cast
    #params[:id] = #id
    @spell = Spell.find(params[:id])
  end

  private

  def useable_spells
    @spells = current_user.user_spells.where(owned:true)
    @spells = Hash.new
    @spells['self'] = Spell.target_self
    @spells['enemy'] = Spell.target_enemy
    @spells['friend'] = Spell.target_friend
  end

  def owned_spells
    @owned = current_user.user_spells.where(owned:true)
    if @owned.present?
      spells = @owned.map { |us| us.spell }
    else
      spells = {}
    end
    @spells = Hash.new
    s_self = Array.new
    enemy = Array.new
    friend = Array.new
    spells.each do |spell|
      s_self.push(spell) if spell.target == 'self'
      enemy = spell if spell.target == 'enemy'
      friend = spell if spell.target == 'friend'
    end
    @spells['self'] = s_self
  end

end

app/views/spells/_spell_list.html.haml
.panel.panel-default
  .panel-heading
    Spells
  .panel-body
    -@spells.each do |key, spells|
      .panel-heading
        =key
      -spells.each do |spell|
        %dl.dl-horizontal
          %dt
            = link_to "Cast #{spell.name}", cast_spell_path(spell),
              :remote => true, data: {toggle: "modal", target:"#spell-modal"}, class: "btn btn-default load-spell"
          %dd
            =spell.description

app/views/spells/_spell_modal.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4.modal-title="Casting #{spell.name}"
    .modal-body
      %p
        =spell_form_builder(spell)
    -#.modal-footer
    -#  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} No
    -#  %button.btn.btn-primary{:type => "button"} Yes

app/views/spells/cast.js.erb
$("#spell-modal").html('<%= escape_javascript "#{render 'spell_modal', spell:@spell}".html_safe%>')

app/views/spells/index.html.haml
-if current_user
  .modal.fade#spell-modal
  ="Welcome #{current_user.email}"
  =render "shared/home_pic", page: @page
  =render "homes/stats"
  =render "spell_list"
  =render "shared/back"